"use client"

import { Button } from "@/components/ui/button"
import { Printer } from "lucide-react"

interface PrintReportProps {
  title: string
  content: React.ReactNode
}

export function PrintReport({ title, content }: PrintReportProps) {
  const handlePrint = () => {
    const printWindow = window.open("", "_blank")
    if (!printWindow) return

    const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>${title}</title>
        <style>
          body {
            font-family: Arial, sans-serif;
            margin: 20px;
            color: #333;
          }
          h1 {
            color: #2563eb;
            border-bottom: 2px solid #2563eb;
            padding-bottom: 10px;
          }
          h2 {
            color: #1e40af;
            margin-top: 20px;
            margin-bottom: 10px;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            margin: 15px 0;
          }
          th, td {
            border: 1px solid #ddd;
            padding: 12px;
            text-align: left;
          }
          th {
            background-color: #2563eb;
            color: white;
            font-weight: bold;
          }
          tr:nth-child(even) {
            background-color: #f3f4f6;
          }
          .summary {
            background-color: #f0f9ff;
            border: 1px solid #0284c7;
            padding: 15px;
            margin: 15px 0;
            border-radius: 5px;
          }
          .summary-item {
            display: inline-block;
            margin-right: 30px;
            margin-bottom: 10px;
          }
          .summary-label {
            font-size: 12px;
            color: #666;
          }
          .summary-value {
            font-size: 18px;
            font-weight: bold;
            color: #2563eb;
          }
          .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            font-size: 12px;
            color: #666;
            text-align: center;
          }
          @media print {
            body {
              margin: 0;
              padding: 10px;
            }
          }
        </style>
      </head>
      <body>
        <h1>ReportX Stock - ${title}</h1>
        <p>Generated on: ${new Date().toLocaleString()}</p>
        ${typeof content === "string" ? content : ""}
        <div class="footer">
          <p>This is an automated report generated by ReportX Stock Management System</p>
        </div>
      </body>
      </html>
    `

    printWindow.document.write(htmlContent)
    printWindow.document.close()

    // Wait for content to load before printing
    setTimeout(() => {
      printWindow.print()
    }, 250)
  }

  return (
    <Button onClick={handlePrint} variant="outline" size="sm" className="gap-2">
      <Printer className="h-4 w-4" />
      Print Report
    </Button>
  )
}
